---
title: "Group sequential design"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(pwb)
library(ggplot2)
```

Find single-arm group sequential design with p0=0.5, p1=0.6, type-I error-rate 0.1, power
0.8, with stopping for both benefit and futility:

```{r, single GS}
  ad <- curtailment::singlearmDesign(nmin=50,
                                   nmax=140,
                                   C=20,
                                   minstop=40,
                                   p0=0.5,
                                   p1=0.6,
                                   alpha=0.1,
                                   power=0.8,
                                   minthetaE=1,
                                   maxthetaF=0,
                                   max.combns=1e3)
# Obtain stopping bounds:
  bounds <- curtailment::drawDiagram(ad)
# Find bias for this design, for a single true response probability theta:
  nsims <- 1e5
  single.GS <- pwbGS(theta=0.5, des=ad, bounds=bounds$bounds.mat, nsims=nsims)
  single.GS$ests[, 1:5]
  round(single.GS$mc.error, 5)
```

How does bias compare when the true response probability is varied? Find results for a vector of true response probabilities:

```{r, multiple GS}
theta.vec <- seq(0.2, 0.8, 0.1) # Vector of true response probabilities
summary.data <- raw.data <- vector("list", length(theta.vec))
stop.early.count <- rep(NA, length(theta.vec))
set.seed(53)

for(i in 1:length(theta.vec)){
  one.run <- pwbGS(theta=theta.vec[i], des=ad, bounds=bounds$bounds.mat, nsims=nsims)
  summary.data[[i]] <- one.run$ests
  stop.early.count[i] <- one.run$ests["Stopped early", "nsims"]/nsims
}

all.gs <- do.call(rbind, summary.data)
```

Plot the results:

```{r GS plot, fig.height=4, fig.width=6}
#### Plot bias for all theta values ####
gs.plot <- ggplot(data=all.gs, mapping=aes(x=theta, y=bias, col=type))+
  geom_line(alpha=0.4, size=1)+
  geom_point()+
  labs(x="True response probability theta",
       y="Bias (estimate - theta)",
       title="Bias in GS design",
       subtitle="Includes proportion of trials stopped early")+
  annotate("text", x=theta.vec, y=-0.15, label=round(stop.early.count,2))+
  geom_vline(aes(xintercept=0.5), col="grey", linetype="dashed")+
  geom_vline(aes(xintercept=0.6), col="grey", linetype="dashed")+
  geom_hline(aes(yintercept=0), col="grey", linetype="dashed")+
  scale_x_continuous(breaks=theta.vec)
gs.plot

#### Plot bias -- no subsetting of "stopped early" or "stopped at N" ####
gs.plot2 <- ggplot(data=all.gs[all.gs$type %in% c("All (naive)", "All (precision-weghted)"), ],
                   mapping=aes(x=theta, y=bias, col=type))+
  geom_line(alpha=0.4, size=1)+
  geom_point()+
  labs(x="True response probability theta",
       y="Bias (estimate - theta)",
       title="Bias in GS design",
       subtitle="Includes proportion of trials stopped early")+
  annotate("text", x=theta.vec, y=-0.01, label=round(stop.early.count,2))+
  geom_vline(aes(xintercept=0.5), col="grey", linetype="dashed")+
  geom_vline(aes(xintercept=0.6), col="grey", linetype="dashed")+
  geom_hline(aes(yintercept=0), col="grey", linetype="dashed")+
  scale_x_continuous(breaks=theta.vec)
gs.plot2
```

