---
title: "Meta-analysis: Simon design"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MA_simon}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(pwb)
```

Find a Simon design with p0=0.5, p1=0.6, type-I error-rate 0.05, power
0.9:

```{r, simon}
all.designs <- clinfun::ph2simon(pu=0.5,
                                 pa=0.6,
                                 ep1=0.05,
                                 ep2=0.1,
                                 nmax=500)
# Choose optimal Simon design:
opt.index <- which.min(all.designs$out[, "EN(p0)"])
simon.des <- all.designs$out[opt.index, ]
```

Now simulate meta-analyses of a single Simon design and some number of single-arm single-stage trials with the same maximum sample size _N_ as the Simon design. We also choose the true response probability theta.

```{r}
ma.simon.results <- maSimon(theta=0.5,
                            des=simon.des,
                            nsims=1e4,
                            n.studies=4)
ma.simon.results
```

